# Generated by Django 6.1.1 on 2026-09-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_researchstep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResearchStep',
            new_name='InquiryStep',
        ),
        migrations.AlterModelOptions(
            name='inquirystep',
            options={'ordering': ['-created']},
        ),
    ]
